POST http://localhost:8787/alumnos
Content-Type: application/json

{
	"nombres": "Abraham",
	"apellidos": "Espinosa Mendoza",
	"matricula": "A21216408",
	"promedio": 93,
	"password": "securePassword123"
}

###
POST http://localhost:8787/alumnos/34/email

###
GET http://localhost:8787/alumnos

###
PUT http://localhost:8787/alumnos/1
Content-Type: application/json

{
	"nombres": "Adriana Guadalupe",
	"apellidos": "Guzmán Morales",
	"matricula": "A21216409",
	"promedio": 99,
	"password": "securePassword123"
}

###
GET http://localhost:8787/alumnos/1

###
DELETE http://localhost:8787/alumnos/1

###
GET http://localhost:8787/alumnos