GET http://localhost:8787/alumnos/1

###
DELETE http://localhost:8787/alumnos

###
POST http://localhost:8787/alumnos
Content-Type: application/json

{
	"id": 1,
	"nombres": "Luis Fernando",
	"apellidos": "",
	"matricula": "A21216408",
	"promedio": 93
}

###
PUT http://localhost:8787/alumnos/1
Content-Type: application/json

{
	"id": 1,
	"nombres": "Abraham",
	"apellidos": "Espinosa Mendoza",
	"matricula": "A21216408",
	"promedio": 101
}
